# Generated by Django 5.1.6 on 2025-03-02 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masjid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=255, unique=True)),
                ('district', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('masjid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masjid.masjid')),
            ],
        ),
    ]
