# Generated by Django 5.1.6 on 2025-03-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Masjid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('location_url', models.CharField(max_length=1000)),
                ('contact', models.CharField(blank=True, default="ma'lumot yo'q", max_length=255, null=True)),
                ('bomdod', models.CharField(default='vaqt', max_length=255)),
                ('quyosh', models.CharField(default='vaqt', max_length=255)),
                ('peshin', models.CharField(default='vaqt', max_length=255)),
                ('asr', models.CharField(default='vaqt', max_length=255)),
                ('shom', models.CharField(default='vaqt', max_length=255)),
                ('xufton', models.CharField(default='vaqt', max_length=255)),
            ],
        ),
    ]
